language: node_js
node_js:
    - stable

services:
    - redis-server

install:
    - npm install -g codecov
    - npm ci

script:
    - npm run lint
    - npm run test-all
    - npm run report-coverage
    - codecov
