version: '3.7'

services:
    redis:
        container_name: 'jira_bot_redis'
        image: 'redis'
        ports:
            - 6378:6379
        volumes:
            - 'jira_bot_redisdata:/data'
        networks:
            - mynetwork
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "npm run start"
        container_name: 'jira_bot_app'
        depends_on:
            - redis
        volumes:
            - '~/.bash_history:/.bash_history'
            - '/tmp:/tmp:delegated'
        ports:
            - 4100:4100
        networks:
            - mynetwork

volumes:
    jira_bot_redisdata:

networks:
    mynetwork:
        external: true
