version: '3.3'

services:
    jira_bot_app:
        image: node:13.5.0
        working_dir: /usr/src/app
        container_name: jira_bot_app
        command: sh -c "npm run start-dev"
        volumes:
            - '~/.bash_history:/.bash_history'
            - './:/usr/src/app:delegated'
            - '/tmp:/tmp:delegated'
        depends_on:
            - redis_db_jira
        ports:
            - 54100:54100
        networks:
            - mynetwork
    redis_db_jira:
        image: redis:4.0.11-alpine
        container_name: redis_db_jira
        ports:
            - '6379:6379'
        volumes:
            - redis_bot:/data
        user: redis
        networks:
            - mynetwork

volumes:
    redis_bot:

networks:
    mynetwork:
        external: false
